languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://djherbis.com/"
canonifyurls = true
title = "djherbis"
author = "admin"
theme = "hugo-theme-pixyll"


[indexes]
  category = "categories"
  tag = "tags"